imageset:
  name: imageset
  read: source
  write: destination
  registries:
    source:
      url: docker.io
      auth: xyz
      namespace: sourceNamespace
    destination:
      url: quay.io
      auth: xyz
      namespace: destinationNamespace
  images:
    - x
    - y
    - z